# Generated by Django 5.1 on 2024-09-15 04:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_booking_number_of_guests_alter_menu_inventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="prince",
            new_name="price",
        ),
    ]
