# Generated by Django 5.1 on 2024-09-15 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_rename_prince_menu_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="MenuItem",
        ),
    ]
